import type { Metadata } from "next";
import { Poppins} from "next/font/google";
import {GlobalStyle} from "./resetCss/resetAllCss";
import StyledComponentsRegistry from "./lib/registry";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} h-full antialiased`}
    >
      <StyledComponentsRegistry>
        <GlobalStyle />
          <body>
            {children}
          </body>
      </StyledComponentsRegistry>
    </html>
  );
}
