import type { Metadata } from "next";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { Poppins } from "next/font/google";
import { GlobalStyle } from "../../styles/resetAllCss";
import StyledComponentsRegistry from "../../lib/registry";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import { routing } from "@/i18n/routing";

const baseUrl = process.env.NEXT_PUBLIC_API_URL;

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default: "Next.js App",
    template: "%s | Next.js App",
  },
  description: "Generated by create next app",

  //search gg SEO
  keywords: ["next.js", "react", "typescript"],
  twitter: {
    card: "summary_large_image",
  },

  //Share in social network
  openGraph: {
    title: "Next.js App",
    description: "Generated by create next app",
    url: `${baseUrl}`,
    siteName: "Next.js App",
    images: {
      url: `${baseUrl}/og-image.png`,
      width: 1200,
      height: 630,
      alt: "Next.js App",
    },
    locale: "vn-VN",
    phoneNumbers: "+84 902914017",
    emails: "akiethuynh0904@gmail.com",
    type: "website",
    countryName: "Vietnam",
  },

  // sinh thêm link không bị nhiều link
  alternates: {
    canonical: `${baseUrl}`,
    languages: {
      "en-US": `${baseUrl}/en`,
      "vi-VN": `${baseUrl}/vi`,
    },
  },

  // định nghĩa URL gốc cho metadata
  metadataBase: new URL(`${baseUrl}`),
};

// Cấu hình viewport để đảm bảo trang web hiển thị tốt trên các thiết bị di động
export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}>) {
  const {locale} = await params;

  if(!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const messages = (await import(`@/messages/${locale}.json`)).default;

  return (
    <html
      lang={locale}
      className={`${poppins.variable} antialiased`}
    >
      <NextIntlClientProvider locale={locale} messages={messages}>
        <StyledComponentsRegistry>
          <GlobalStyle /> 
            <body>
              <Navbar/>
              {children}
              <Footer />
            </body>
        </StyledComponentsRegistry>
      </NextIntlClientProvider>
    </html>
  );
}
